import {
  pbkdf2 as pbkdf2Callback,
  randomBytes,
  scrypt as scryptCallback,
  timingSafeEqual,
  type ScryptOptions,
} from "node:crypto";
import { promisify } from "node:util";

const scrypt = promisify(scryptCallback) as (
  password: string,
  salt: Buffer,
  keylen: number,
  options: ScryptOptions,
) => Promise<Buffer>;

const pbkdf2 = promisify(pbkdf2Callback) as (
  password: string,
  salt: Buffer,
  iterations: number,
  keylen: number,
  digest: string,
) => Promise<Buffer>;

/**
 * Password hashing on Node's built-in scrypt.
 *
 * Deliberately not bcrypt or argon2: both are native modules, and this app is
 * built on Windows and shipped in an Alpine container, so a prebuilt binary
 * that exists on one and not the other is a recurring build failure for no
 * security gain. scrypt is memory-hard, in core, and needs no toolchain.
 *
 * Encoded as `scrypt$N$salt$key` with salt and key in base64url, so the cost
 * travels with the hash and existing rows stay verifiable after it is raised.
 */
const KEY_LENGTH = 64;
const SALT_LENGTH = 16;
const COST = 16_384; // N, must be a power of two
const BLOCK_SIZE = 8; // r
const PARALLELISM = 1; // p

function options(cost: number): ScryptOptions {
  return {
    N: cost,
    r: BLOCK_SIZE,
    p: PARALLELISM,
    // Node's 32MB default is below what N=16384, r=8 needs (128 * N * r).
    maxmem: 256 * cost * BLOCK_SIZE,
  };
}

export async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(SALT_LENGTH);
  const key = await scrypt(password.normalize("NFKC"), salt, KEY_LENGTH, options(COST));
  return ["scrypt", COST, salt.toString("base64url"), key.toString("base64url")].join("$");
}

/**
 * Django's PBKDF2, read but never written.
 *
 * The app this one replaces stored `pbkdf2_sha256$<iterations>$<salt>$<key>`,
 * and the people migrated out of it have to be able to sign in. The
 * alternative was to reset seven passwords by email, and there is no mail
 * transport -- so the alternative was actually to lock everybody out.
 *
 * Two details are easy to get wrong and are why this is tested against a
 * vector generated by the old app's own Django rather than from memory: the
 * salt is used as its literal text, not decoded from base64, and the key is
 * standard base64 rather than the base64url the scrypt format uses.
 *
 * This is a read path only. `hashPassword` always writes scrypt, `needsRehash`
 * already reports true for any other scheme, and sign-in re-hashes on the
 * first success -- so a migrated hash survives exactly one login.
 */
async function verifyDjangoPbkdf2(
  password: string,
  iterationsPart: string,
  saltPart: string,
  keyPart: string,
): Promise<boolean> {
  const iterations = Number(iterationsPart);
  if (!Number.isInteger(iterations) || iterations < 1 || iterations > 10_000_000) return false;

  const expected = Buffer.from(keyPart, "base64");
  if (expected.length === 0) return false;

  const actual = await pbkdf2(
    password.normalize("NFKC"),
    Buffer.from(saltPart, "utf8"),
    iterations,
    expected.length,
    "sha256",
  );

  return expected.length === actual.length && timingSafeEqual(expected, actual);
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, costPart, saltPart, keyPart] = stored.split("$");
  if (!costPart || !saltPart || !keyPart) return false;

  if (scheme === "pbkdf2_sha256") {
    return verifyDjangoPbkdf2(password, costPart, saltPart, keyPart);
  }

  if (scheme !== "scrypt") return false;

  const cost = Number(costPart);
  if (!Number.isInteger(cost) || cost < 2 || (cost & (cost - 1)) !== 0) return false;

  const expected = Buffer.from(keyPart, "base64url");
  const actual = await scrypt(
    password.normalize("NFKC"),
    Buffer.from(saltPart, "base64url"),
    expected.length,
    options(cost),
  );

  return expected.length === actual.length && timingSafeEqual(expected, actual);
}

/** True when a stored hash was made with a weaker cost and should be upgraded on next login. */
export function needsRehash(stored: string): boolean {
  const [scheme, costPart] = stored.split("$");
  return scheme !== "scrypt" || Number(costPart) < COST;
}
